[2025-08-10T06:14:55.848+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-10T06:14:53.789566+00:00 [queued]>
[2025-08-10T06:14:55.854+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-10T06:14:53.789566+00:00 [queued]>
[2025-08-10T06:14:55.854+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-08-10T06:14:55.864+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-10 06:14:53.789566+00:00
[2025-08-10T06:14:55.869+0000] {standard_task_runner.py:57} INFO - Started process 5404 to run task
[2025-08-10T06:14:55.872+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2025-08-10T06:14:53.789566+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmpd3p_ys9j']
[2025-08-10T06:14:55.874+0000] {standard_task_runner.py:85} INFO - Job 19: Subtask python_job
[2025-08-10T06:14:55.938+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job manual__2025-08-10T06:14:53.789566+00:00 [running]> on host 95fb1ebfe85f
[2025-08-10T06:14:56.019+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-10T06:14:53.789566+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-10T06:14:53.789566+00:00'
[2025-08-10T06:14:56.031+0000] {base.py:73} INFO - Using connection ID 'spark-conn' for task execution.
[2025-08-10T06:14:56.033+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master spark://sparkling-spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py
[2025-08-10T06:14:56.392+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-10T06:14:59.133+0000] {spark_submit.py:579} INFO - Using Spark's default log4j profile: org/apache/spark/log4j2-defaults.properties
[2025-08-10T06:14:59.142+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SparkContext: Running Spark version 4.0.0
[2025-08-10T06:14:59.146+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SparkContext: OS info Linux, 6.6.87.2-microsoft-standard-WSL2, amd64
[2025-08-10T06:14:59.147+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SparkContext: Java version 17.0.15
[2025-08-10T06:14:59.220+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-08-10T06:14:59.265+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO ResourceUtils: ==============================================================
[2025-08-10T06:14:59.266+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-08-10T06:14:59.267+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO ResourceUtils: ==============================================================
[2025-08-10T06:14:59.267+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SparkContext: Submitted application: PythonWordCount
[2025-08-10T06:14:59.290+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-08-10T06:14:59.293+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO ResourceProfile: Limiting resource is cpu
[2025-08-10T06:14:59.295+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-08-10T06:14:59.332+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: Changing view acls to: ***
[2025-08-10T06:14:59.333+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: Changing modify acls to: ***
[2025-08-10T06:14:59.334+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-10T06:14:59.334+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-10T06:14:59.336+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-10T06:14:59.526+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO Utils: Successfully started service 'sparkDriver' on port 36421.
[2025-08-10T06:14:59.552+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SparkEnv: Registering MapOutputTracker
[2025-08-10T06:14:59.562+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SparkEnv: Registering BlockManagerMaster
[2025-08-10T06:14:59.580+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-08-10T06:14:59.580+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-08-10T06:14:59.583+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-08-10T06:14:59.604+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-3dbd5470-be9b-45e7-ba73-b60c0b351f57
[2025-08-10T06:14:59.624+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-08-10T06:14:59.727+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-08-10T06:14:59.784+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-08-10T06:14:59.825+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: Changing view acls to: ***
[2025-08-10T06:14:59.826+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: Changing modify acls to: ***
[2025-08-10T06:14:59.826+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: Changing view acls groups to: ***
[2025-08-10T06:14:59.827+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: Changing modify acls groups to: ***
[2025-08-10T06:14:59.827+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: *** groups with view permissions: EMPTY; users with modify permissions: ***; groups with modify permissions: EMPTY; RPC SSL disabled
[2025-08-10T06:14:59.957+0000] {spark_submit.py:579} INFO - 25/08/10 06:14:59 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://sparkling-spark-master-1:7077...
[2025-08-10T06:15:00.013+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:00 INFO TransportClientFactory: Successfully created connection to sparkling-spark-master-1/172.18.0.2:7077 after 27 ms (0 ms spent in bootstraps)
[2025-08-10T06:15:01.513+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250810061501-0000
[2025-08-10T06:15:01.520+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 42641.
[2025-08-10T06:15:01.521+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO NettyBlockTransferService: Server created on 95fb1ebfe85f:42641
[2025-08-10T06:15:01.522+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-08-10T06:15:01.534+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 95fb1ebfe85f, 42641, None)
[2025-08-10T06:15:01.539+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO BlockManagerMasterEndpoint: Registering block manager 95fb1ebfe85f:42641 with 434.4 MiB RAM, BlockManagerId(driver, 95fb1ebfe85f, 42641, None)
[2025-08-10T06:15:01.542+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 95fb1ebfe85f, 42641, None)
[2025-08-10T06:15:01.543+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 95fb1ebfe85f, 42641, None)
[2025-08-10T06:15:01.662+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-08-10T06:15:01.753+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250810061501-0000/0 on worker-20250809234214-172.18.0.5-39995 (172.18.0.5:39995) with 2 core(s)
[2025-08-10T06:15:01.754+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:01 INFO StandaloneSchedulerBackend: Granted executor ID app-20250810061501-0000/0 on hostPort 172.18.0.5:39995 with 2 core(s), 1024.0 MiB RAM
[2025-08-10T06:15:04.409+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO SparkContext: Starting job: collect at /opt/***/jobs/python/wordcountjob.py:11
[2025-08-10T06:15:04.454+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO DAGScheduler: Registering RDD 2 (reduceByKey at /opt/***/jobs/python/wordcountjob.py:9) as input to shuffle 0
[2025-08-10T06:15:04.465+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO DAGScheduler: Got job 0 (collect at /opt/***/jobs/python/wordcountjob.py:11) with 2 output partitions
[2025-08-10T06:15:04.469+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO DAGScheduler: Final stage: ResultStage 1 (collect at /opt/***/jobs/python/wordcountjob.py:11)
[2025-08-10T06:15:04.472+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO DAGScheduler: Parents of final stage: List(ShuffleMapStage 0)
[2025-08-10T06:15:04.479+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO DAGScheduler: Missing parents: List(ShuffleMapStage 0)
[2025-08-10T06:15:04.484+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO DAGScheduler: Submitting ShuffleMapStage 0 (PairwiseRDD[2] at reduceByKey at /opt/***/jobs/python/wordcountjob.py:9), which has no missing parents
[2025-08-10T06:15:04.546+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-08-10T06:15:04.595+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO MemoryStore: Block broadcast_0 stored as values in memory (estimated size 10.1 KiB, free 434.4 MiB)
[2025-08-10T06:15:04.682+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO MemoryStore: Block broadcast_0_piece0 stored as bytes in memory (estimated size 6.2 KiB, free 434.4 MiB)
[2025-08-10T06:15:04.695+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO SparkContext: Created broadcast 0 from broadcast at DAGScheduler.scala:1676
[2025-08-10T06:15:04.719+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO DAGScheduler: Submitting 2 missing tasks from ShuffleMapStage 0 (PairwiseRDD[2] at reduceByKey at /opt/***/jobs/python/wordcountjob.py:9) (first 15 tasks are for partitions Vector(0, 1))
[2025-08-10T06:15:04.732+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO TaskSchedulerImpl: Adding task set 0.0 with 2 tasks resource profile 0
[2025-08-10T06:15:04.807+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:04 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250810061501-0000/0 is now RUNNING
[2025-08-10T06:15:07.674+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:07 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Registered executor NettyRpcEndpointRef(spark-client://Executor) (172.18.0.5:54850) with ID 0, ResourceProfileId 0
[2025-08-10T06:15:07.833+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:07 INFO BlockManagerMasterEndpoint: Registering block manager 172.18.0.5:40485 with 434.4 MiB RAM, BlockManagerId(0, 172.18.0.5, 40485, None)
[2025-08-10T06:15:07.910+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:07 INFO TaskSetManager: Starting task 0.0 in stage 0.0 (TID 0) (172.18.0.5,executor 0, partition 0, PROCESS_LOCAL, 9735 bytes)
[2025-08-10T06:15:07.915+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:07 INFO TaskSetManager: Starting task 1.0 in stage 0.0 (TID 1) (172.18.0.5,executor 0, partition 1, PROCESS_LOCAL, 9768 bytes)
[2025-08-10T06:15:09.817+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 WARN TaskSetManager: Lost task 1.0 in stage 0.0 (TID 1) (172.18.0.5 executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2025-08-10T06:15:09.818+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.818+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.818+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.819+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.819+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.819+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.820+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:09.820+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:581)
[2025-08-10T06:15:09.820+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:940)
[2025-08-10T06:15:09.821+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:925)
[2025-08-10T06:15:09.821+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:532)
[2025-08-10T06:15:09.823+0000] {spark_submit.py:579} INFO - at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2025-08-10T06:15:09.824+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:263)
[2025-08-10T06:15:09.824+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:265)
[2025-08-10T06:15:09.831+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
[2025-08-10T06:15:09.831+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
[2025-08-10T06:15:09.832+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
[2025-08-10T06:15:09.832+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
[2025-08-10T06:15:09.833+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
[2025-08-10T06:15:09.833+0000] {spark_submit.py:579} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
[2025-08-10T06:15:09.834+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:147)
[2025-08-10T06:15:09.834+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
[2025-08-10T06:15:09.834+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
[2025-08-10T06:15:09.835+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
[2025-08-10T06:15:09.835+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
[2025-08-10T06:15:09.836+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
[2025-08-10T06:15:09.836+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-08-10T06:15:09.837+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-08-10T06:15:09.837+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-08-10T06:15:09.837+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:09.838+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Starting task 1.1 in stage 0.0 (TID 2) (172.18.0.5,executor 0, partition 1, PROCESS_LOCAL, 9768 bytes)
[2025-08-10T06:15:09.838+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Lost task 0.0 in stage 0.0 (TID 0) on 172.18.0.5, executor 0: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
[2025-08-10T06:15:09.838+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.839+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.839+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.839+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.840+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.840+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.840+0000] {spark_submit.py:579} INFO - ) [duplicate 1]
[2025-08-10T06:15:09.840+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Starting task 0.1 in stage 0.0 (TID 3) (172.18.0.5,executor 0, partition 0, PROCESS_LOCAL, 9735 bytes)
[2025-08-10T06:15:09.849+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Lost task 1.1 in stage 0.0 (TID 2) on 172.18.0.5, executor 0: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
[2025-08-10T06:15:09.851+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.852+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.852+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.853+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.853+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.854+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.854+0000] {spark_submit.py:579} INFO - ) [duplicate 2]
[2025-08-10T06:15:09.855+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Starting task 1.2 in stage 0.0 (TID 4) (172.18.0.5,executor 0, partition 1, PROCESS_LOCAL, 9768 bytes)
[2025-08-10T06:15:09.856+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Lost task 0.1 in stage 0.0 (TID 3) on 172.18.0.5, executor 0: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
[2025-08-10T06:15:09.859+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.859+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.860+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.861+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.862+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.862+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.863+0000] {spark_submit.py:579} INFO - ) [duplicate 3]
[2025-08-10T06:15:09.863+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Starting task 0.2 in stage 0.0 (TID 5) (172.18.0.5,executor 0, partition 0, PROCESS_LOCAL, 9735 bytes)
[2025-08-10T06:15:09.882+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Lost task 1.2 in stage 0.0 (TID 4) on 172.18.0.5, executor 0: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
[2025-08-10T06:15:09.883+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.884+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.885+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.885+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.886+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.886+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.887+0000] {spark_submit.py:579} INFO - ) [duplicate 4]
[2025-08-10T06:15:09.887+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Starting task 1.3 in stage 0.0 (TID 6) (172.18.0.5,executor 0, partition 1, PROCESS_LOCAL, 9768 bytes)
[2025-08-10T06:15:09.889+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Lost task 0.2 in stage 0.0 (TID 5) on 172.18.0.5, executor 0: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
[2025-08-10T06:15:09.890+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.891+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.892+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.893+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.894+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.894+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.895+0000] {spark_submit.py:579} INFO - ) [duplicate 5]
[2025-08-10T06:15:09.895+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Starting task 0.3 in stage 0.0 (TID 7) (172.18.0.5,executor 0, partition 0, PROCESS_LOCAL, 9735 bytes)
[2025-08-10T06:15:09.908+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Lost task 1.3 in stage 0.0 (TID 6) on 172.18.0.5, executor 0: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
[2025-08-10T06:15:09.911+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.912+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.913+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.913+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.913+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.914+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.914+0000] {spark_submit.py:579} INFO - ) [duplicate 6]
[2025-08-10T06:15:09.914+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 ERROR TaskSetManager: Task 1 in stage 0.0 failed 4 times; aborting job
[2025-08-10T06:15:09.915+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSchedulerImpl: Canceling stage 0
[2025-08-10T06:15:09.915+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSchedulerImpl: Killing all running tasks in stage 0: Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 6) (172.18.0.5 executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2025-08-10T06:15:09.916+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.916+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.916+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.917+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.917+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.918+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.918+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:09.918+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:581)
[2025-08-10T06:15:09.919+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:940)
[2025-08-10T06:15:09.920+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:925)
[2025-08-10T06:15:09.920+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:532)
[2025-08-10T06:15:09.920+0000] {spark_submit.py:579} INFO - at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2025-08-10T06:15:09.921+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:263)
[2025-08-10T06:15:09.921+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:265)
[2025-08-10T06:15:09.921+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
[2025-08-10T06:15:09.922+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
[2025-08-10T06:15:09.922+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
[2025-08-10T06:15:09.922+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
[2025-08-10T06:15:09.923+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
[2025-08-10T06:15:09.923+0000] {spark_submit.py:579} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
[2025-08-10T06:15:09.924+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:147)
[2025-08-10T06:15:09.924+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
[2025-08-10T06:15:09.924+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
[2025-08-10T06:15:09.925+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
[2025-08-10T06:15:09.926+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
[2025-08-10T06:15:09.926+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
[2025-08-10T06:15:09.926+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-08-10T06:15:09.927+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-08-10T06:15:09.927+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-08-10T06:15:09.927+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:09.928+0000] {spark_submit.py:579} INFO - Driver stacktrace:
[2025-08-10T06:15:09.928+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSchedulerImpl: Removed TaskSet 0.0 whose tasks have all completed, from pool
[2025-08-10T06:15:09.928+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSchedulerImpl: Stage 0.0 was cancelled
[2025-08-10T06:15:09.929+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSetManager: Lost task 0.3 in stage 0.0 (TID 7) on 172.18.0.5, executor 0: org.apache.spark.api.python.PythonException (Traceback (most recent call last):
[2025-08-10T06:15:09.929+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.929+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.929+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.930+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.930+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.930+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.930+0000] {spark_submit.py:579} INFO - ) [duplicate 7]
[2025-08-10T06:15:09.930+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO TaskSchedulerImpl: Removed TaskSet 0.0 whose tasks have all completed, from pool
[2025-08-10T06:15:09.931+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO DAGScheduler: ShuffleMapStage 0 (reduceByKey at /opt/***/jobs/python/wordcountjob.py:9) failed in 5410 ms due to Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 6) (172.18.0.5 executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2025-08-10T06:15:09.931+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.932+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.932+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.932+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.932+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.933+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.933+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:09.933+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:581)
[2025-08-10T06:15:09.933+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:940)
[2025-08-10T06:15:09.934+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:925)
[2025-08-10T06:15:09.934+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:532)
[2025-08-10T06:15:09.934+0000] {spark_submit.py:579} INFO - at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2025-08-10T06:15:09.934+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:263)
[2025-08-10T06:15:09.935+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:265)
[2025-08-10T06:15:09.935+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
[2025-08-10T06:15:09.935+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
[2025-08-10T06:15:09.935+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
[2025-08-10T06:15:09.936+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
[2025-08-10T06:15:09.936+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
[2025-08-10T06:15:09.936+0000] {spark_submit.py:579} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
[2025-08-10T06:15:09.937+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:147)
[2025-08-10T06:15:09.937+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
[2025-08-10T06:15:09.937+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
[2025-08-10T06:15:09.937+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
[2025-08-10T06:15:09.938+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
[2025-08-10T06:15:09.938+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
[2025-08-10T06:15:09.938+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-08-10T06:15:09.938+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-08-10T06:15:09.938+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-08-10T06:15:09.939+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:09.939+0000] {spark_submit.py:579} INFO - Driver stacktrace:
[2025-08-10T06:15:09.939+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:09 INFO DAGScheduler: Job 0 failed: collect at /opt/***/jobs/python/wordcountjob.py:11, took 5513.858826 ms
[2025-08-10T06:15:09.981+0000] {spark_submit.py:579} INFO - Traceback (most recent call last):
[2025-08-10T06:15:09.982+0000] {spark_submit.py:579} INFO - File "/opt/***/jobs/python/wordcountjob.py", line 11, in <module>
[2025-08-10T06:15:09.984+0000] {spark_submit.py:579} INFO - for wc in wordCounts.collect():
[2025-08-10T06:15:09.984+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/core/rdd.py", line 1700, in collect
[2025-08-10T06:15:09.986+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.9-src.zip/py4j/java_gateway.py", line 1362, in __call__
[2025-08-10T06:15:09.987+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 282, in deco
[2025-08-10T06:15:09.988+0000] {spark_submit.py:579} INFO - File "/home/***/.local/lib/python3.10/site-packages/pyspark/python/lib/py4j-0.10.9.9-src.zip/py4j/protocol.py", line 327, in get_return_value
[2025-08-10T06:15:09.990+0000] {spark_submit.py:579} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling z:org.apache.spark.api.python.PythonRDD.collectAndServe.
[2025-08-10T06:15:09.990+0000] {spark_submit.py:579} INFO - : org.apache.spark.SparkException: Job aborted due to stage failure: Task 1 in stage 0.0 failed 4 times, most recent failure: Lost task 1.3 in stage 0.0 (TID 6) (172.18.0.5 executor 0): org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2025-08-10T06:15:09.990+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:09.991+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:09.991+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:09.991+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:09.992+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:09.992+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:09.992+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:09.993+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:581)
[2025-08-10T06:15:09.993+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:940)
[2025-08-10T06:15:09.993+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:925)
[2025-08-10T06:15:09.994+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:532)
[2025-08-10T06:15:09.994+0000] {spark_submit.py:579} INFO - at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2025-08-10T06:15:09.994+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:263)
[2025-08-10T06:15:09.994+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:265)
[2025-08-10T06:15:09.994+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
[2025-08-10T06:15:09.995+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
[2025-08-10T06:15:09.995+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
[2025-08-10T06:15:09.995+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
[2025-08-10T06:15:09.995+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
[2025-08-10T06:15:09.996+0000] {spark_submit.py:579} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
[2025-08-10T06:15:09.996+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:147)
[2025-08-10T06:15:09.996+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
[2025-08-10T06:15:09.996+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
[2025-08-10T06:15:09.997+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
[2025-08-10T06:15:09.997+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
[2025-08-10T06:15:09.997+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
[2025-08-10T06:15:09.997+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-08-10T06:15:09.997+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-08-10T06:15:09.998+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-08-10T06:15:09.998+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:09.998+0000] {spark_submit.py:579} INFO - Driver stacktrace:
[2025-08-10T06:15:09.998+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$3(DAGScheduler.scala:2935)
[2025-08-10T06:15:09.999+0000] {spark_submit.py:579} INFO - at scala.Option.getOrElse(Option.scala:201)
[2025-08-10T06:15:09.999+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2(DAGScheduler.scala:2935)
[2025-08-10T06:15:09.999+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$abortStage$2$adapted(DAGScheduler.scala:2927)
[2025-08-10T06:15:09.999+0000] {spark_submit.py:579} INFO - at scala.collection.immutable.List.foreach(List.scala:334)
[2025-08-10T06:15:09.999+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGScheduler.abortStage(DAGScheduler.scala:2927)
[2025-08-10T06:15:10.000+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1(DAGScheduler.scala:1295)
[2025-08-10T06:15:10.000+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGScheduler.$anonfun$handleTaskSetFailed$1$adapted(DAGScheduler.scala:1295)
[2025-08-10T06:15:10.000+0000] {spark_submit.py:579} INFO - at scala.Option.foreach(Option.scala:437)
[2025-08-10T06:15:10.000+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGScheduler.handleTaskSetFailed(DAGScheduler.scala:1295)
[2025-08-10T06:15:10.001+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.doOnReceive(DAGScheduler.scala:3207)
[2025-08-10T06:15:10.001+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3141)
[2025-08-10T06:15:10.001+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGSchedulerEventProcessLoop.onReceive(DAGScheduler.scala:3130)
[2025-08-10T06:15:10.001+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.EventLoop$$anon$1.run(EventLoop.scala:50)
[2025-08-10T06:15:10.002+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.DAGScheduler.runJob(DAGScheduler.scala:1009)
[2025-08-10T06:15:10.002+0000] {spark_submit.py:579} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2484)
[2025-08-10T06:15:10.002+0000] {spark_submit.py:579} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2505)
[2025-08-10T06:15:10.002+0000] {spark_submit.py:579} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2524)
[2025-08-10T06:15:10.002+0000] {spark_submit.py:579} INFO - at org.apache.spark.SparkContext.runJob(SparkContext.scala:2549)
[2025-08-10T06:15:10.003+0000] {spark_submit.py:579} INFO - at org.apache.spark.rdd.RDD.$anonfun$collect$1(RDD.scala:1057)
[2025-08-10T06:15:10.003+0000] {spark_submit.py:579} INFO - at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:151)
[2025-08-10T06:15:10.003+0000] {spark_submit.py:579} INFO - at org.apache.spark.rdd.RDDOperationScope$.withScope(RDDOperationScope.scala:112)
[2025-08-10T06:15:10.003+0000] {spark_submit.py:579} INFO - at org.apache.spark.rdd.RDD.withScope(RDD.scala:417)
[2025-08-10T06:15:10.003+0000] {spark_submit.py:579} INFO - at org.apache.spark.rdd.RDD.collect(RDD.scala:1056)
[2025-08-10T06:15:10.004+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRDD$.collectAndServe(PythonRDD.scala:203)
[2025-08-10T06:15:10.004+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRDD.collectAndServe(PythonRDD.scala)
[2025-08-10T06:15:10.004+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-08-10T06:15:10.004+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-08-10T06:15:10.004+0000] {spark_submit.py:579} INFO - at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-08-10T06:15:10.005+0000] {spark_submit.py:579} INFO - at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-08-10T06:15:10.005+0000] {spark_submit.py:579} INFO - at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-08-10T06:15:10.005+0000] {spark_submit.py:579} INFO - at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-08-10T06:15:10.005+0000] {spark_submit.py:579} INFO - at py4j.Gateway.invoke(Gateway.java:282)
[2025-08-10T06:15:10.005+0000] {spark_submit.py:579} INFO - at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-08-10T06:15:10.005+0000] {spark_submit.py:579} INFO - at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-08-10T06:15:10.006+0000] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:184)
[2025-08-10T06:15:10.006+0000] {spark_submit.py:579} INFO - at py4j.ClientServerConnection.run(ClientServerConnection.java:108)
[2025-08-10T06:15:10.006+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Thread.java:840)
[2025-08-10T06:15:10.006+0000] {spark_submit.py:579} INFO - Caused by: org.apache.spark.api.python.PythonException: Traceback (most recent call last):
[2025-08-10T06:15:10.006+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker.py", line 1972, in main
[2025-08-10T06:15:10.007+0000] {spark_submit.py:579} INFO - check_python_version(infile)
[2025-08-10T06:15:10.007+0000] {spark_submit.py:579} INFO - File "/opt/bitnami/spark/python/lib/pyspark.zip/pyspark/worker_util.py", line 77, in check_python_version
[2025-08-10T06:15:10.007+0000] {spark_submit.py:579} INFO - raise PySparkRuntimeError(
[2025-08-10T06:15:10.008+0000] {spark_submit.py:579} INFO - pyspark.errors.exceptions.base.PySparkRuntimeError: [PYTHON_VERSION_MISMATCH] Python in worker has different version: 3.12 than that in driver: 3.10, PySpark cannot run with different minor versions.
[2025-08-10T06:15:10.008+0000] {spark_submit.py:579} INFO - Please check environment variables PYSPARK_PYTHON and PYSPARK_DRIVER_PYTHON are correctly set.
[2025-08-10T06:15:10.008+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:10.009+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.handlePythonException(PythonRunner.scala:581)
[2025-08-10T06:15:10.009+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:940)
[2025-08-10T06:15:10.009+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.PythonRunner$$anon$3.read(PythonRunner.scala:925)
[2025-08-10T06:15:10.009+0000] {spark_submit.py:579} INFO - at org.apache.spark.api.python.BasePythonRunner$ReaderIterator.hasNext(PythonRunner.scala:532)
[2025-08-10T06:15:10.010+0000] {spark_submit.py:579} INFO - at org.apache.spark.InterruptibleIterator.hasNext(InterruptibleIterator.scala:37)
[2025-08-10T06:15:10.010+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.fill(Iterator.scala:263)
[2025-08-10T06:15:10.010+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$GroupedIterator.hasNext(Iterator.scala:265)
[2025-08-10T06:15:10.010+0000] {spark_submit.py:579} INFO - at scala.collection.Iterator$$anon$9.hasNext(Iterator.scala:583)
[2025-08-10T06:15:10.010+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.sort.BypassMergeSortShuffleWriter.write(BypassMergeSortShuffleWriter.java:143)
[2025-08-10T06:15:10.011+0000] {spark_submit.py:579} INFO - at org.apache.spark.shuffle.ShuffleWriteProcessor.write(ShuffleWriteProcessor.scala:57)
[2025-08-10T06:15:10.011+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:111)
[2025-08-10T06:15:10.011+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.ShuffleMapTask.runTask(ShuffleMapTask.scala:54)
[2025-08-10T06:15:10.011+0000] {spark_submit.py:579} INFO - at org.apache.spark.TaskContext.runTaskWithListeners(TaskContext.scala:171)
[2025-08-10T06:15:10.012+0000] {spark_submit.py:579} INFO - at org.apache.spark.scheduler.Task.run(Task.scala:147)
[2025-08-10T06:15:10.012+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.$anonfun$run$5(Executor.scala:647)
[2025-08-10T06:15:10.012+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally(SparkErrorUtils.scala:80)
[2025-08-10T06:15:10.013+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.SparkErrorUtils.tryWithSafeFinally$(SparkErrorUtils.scala:77)
[2025-08-10T06:15:10.013+0000] {spark_submit.py:579} INFO - at org.apache.spark.util.Utils$.tryWithSafeFinally(Utils.scala:99)
[2025-08-10T06:15:10.013+0000] {spark_submit.py:579} INFO - at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:650)
[2025-08-10T06:15:10.013+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
[2025-08-10T06:15:10.013+0000] {spark_submit.py:579} INFO - at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
[2025-08-10T06:15:10.014+0000] {spark_submit.py:579} INFO - at java.base/java.lang.Thread.run(Unknown Source)
[2025-08-10T06:15:10.014+0000] {spark_submit.py:579} INFO - 
[2025-08-10T06:15:10.083+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO SparkContext: Invoking stop() from shutdown hook
[2025-08-10T06:15:10.084+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO SparkContext: SparkContext is stopping with exitCode 0 from run at Executors.java:539.
[2025-08-10T06:15:10.094+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO SparkUI: Stopped Spark web UI at http://95fb1ebfe85f:4040
[2025-08-10T06:15:10.097+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-08-10T06:15:10.097+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-08-10T06:15:10.110+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-08-10T06:15:10.140+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO MemoryStore: MemoryStore cleared
[2025-08-10T06:15:10.140+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO BlockManager: BlockManager stopped
[2025-08-10T06:15:10.148+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-08-10T06:15:10.150+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-08-10T06:15:10.171+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO SparkContext: Successfully stopped SparkContext
[2025-08-10T06:15:10.171+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO ShutdownHookManager: Shutdown hook called
[2025-08-10T06:15:10.172+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO ShutdownHookManager: Deleting directory /tmp/spark-1818a08e-9da8-4f82-87d6-fdf3717cc252
[2025-08-10T06:15:10.189+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO ShutdownHookManager: Deleting directory /tmp/spark-b78d89ab-a91c-468f-847b-62280f4787ef
[2025-08-10T06:15:10.207+0000] {spark_submit.py:579} INFO - 25/08/10 06:15:10 INFO ShutdownHookManager: Deleting directory /tmp/spark-1818a08e-9da8-4f82-87d6-fdf3717cc252/pyspark-b9f2ee5e-a68d-43a6-9ce5-1abaa2591bd5
[2025-08-10T06:15:10.267+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master spark://sparkling-spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.
[2025-08-10T06:15:10.271+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250810T061453, start_date=20250810T061455, end_date=20250810T061510
[2025-08-10T06:15:10.281+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 19 for task python_job (Cannot execute: spark-submit --master spark://sparkling-spark-master-1:7077 --name arrow-spark --deploy-mode client jobs/python/wordcountjob.py. Error code is: 1.; 5404)
[2025-08-10T06:15:10.294+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-10T06:15:10.316+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
