[2025-08-10T12:54:07.063+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-10T12:54:03.391806+00:00 [queued]>
[2025-08-10T12:54:07.073+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: sparking_flow.python_job manual__2025-08-10T12:54:03.391806+00:00 [queued]>
[2025-08-10T12:54:07.073+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-08-10T12:54:07.087+0000] {taskinstance.py:1380} INFO - Executing <Task(SparkSubmitOperator): python_job> on 2025-08-10 12:54:03.391806+00:00
[2025-08-10T12:54:07.092+0000] {standard_task_runner.py:57} INFO - Started process 227 to run task
[2025-08-10T12:54:07.096+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'sparking_flow', 'python_job', 'manual__2025-08-10T12:54:03.391806+00:00', '--job-id', '4', '--raw', '--subdir', 'DAGS_FOLDER/spark_***.py', '--cfg-path', '/tmp/tmp5cj_nbjv']
[2025-08-10T12:54:07.100+0000] {standard_task_runner.py:85} INFO - Job 4: Subtask python_job
[2025-08-10T12:54:07.171+0000] {task_command.py:415} INFO - Running <TaskInstance: sparking_flow.python_job manual__2025-08-10T12:54:03.391806+00:00 [running]> on host a8625f1109c7
[2025-08-10T12:54:07.267+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='Yusuf Ganiyu' AIRFLOW_CTX_DAG_ID='sparking_flow' AIRFLOW_CTX_TASK_ID='python_job' AIRFLOW_CTX_EXECUTION_DATE='2025-08-10T12:54:03.391806+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-08-10T12:54:03.391806+00:00'
[2025-08-10T12:54:07.283+0000] {spark_submit.py:273} INFO - Could not load connection string spark-conn, defaulting to yarn
[2025-08-10T12:54:07.285+0000] {spark_submit.py:403} INFO - Spark-Submit cmd: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py
[2025-08-10T12:54:08.001+0000] {spark_submit.py:579} INFO - WARNING: Using incubator modules: jdk.incubator.vector
[2025-08-10T12:54:09.356+0000] {spark_submit.py:579} INFO - Exception in thread "main" org.apache.spark.SparkException: When running with master 'yarn' either HADOOP_CONF_DIR or YARN_CONF_DIR must be set in the environment.
[2025-08-10T12:54:09.357+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.error(SparkSubmitArguments.scala:640)
[2025-08-10T12:54:09.357+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateSubmitArguments(SparkSubmitArguments.scala:287)
[2025-08-10T12:54:09.357+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.validateArguments(SparkSubmitArguments.scala:245)
[2025-08-10T12:54:09.358+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmitArguments.<init>(SparkSubmitArguments.scala:104)
[2025-08-10T12:54:09.358+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2$$anon$3.<init>(SparkSubmit.scala:1101)
[2025-08-10T12:54:09.358+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.parseArguments(SparkSubmit.scala:1101)
[2025-08-10T12:54:09.359+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.doSubmit(SparkSubmit.scala:72)
[2025-08-10T12:54:09.359+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$$anon$2.doSubmit(SparkSubmit.scala:1132)
[2025-08-10T12:54:09.359+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit$.main(SparkSubmit.scala:1141)
[2025-08-10T12:54:09.359+0000] {spark_submit.py:579} INFO - at org.apache.spark.deploy.SparkSubmit.main(SparkSubmit.scala)
[2025-08-10T12:54:09.388+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/operators/spark_submit.py", line 174, in execute
    self._hook.submit(self.application)
  File "/home/airflow/.local/lib/python3.10/site-packages/airflow/providers/apache/spark/hooks/spark_submit.py", line 505, in submit
    raise AirflowException(
airflow.exceptions.AirflowException: Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.
[2025-08-10T12:54:09.391+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=sparking_flow, task_id=python_job, execution_date=20250810T125403, start_date=20250810T125407, end_date=20250810T125409
[2025-08-10T12:54:09.402+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 4 for task python_job (Cannot execute: spark-submit --master yarn --name arrow-spark jobs/python/wordcountjob.py. Error code is: 1.; 227)
[2025-08-10T12:54:09.436+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-08-10T12:54:09.481+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
